name: Request triage review on beginner and Good First Issue PRs

on:
  pull_request:
    types: [opened, labeled]

concurrency:
  group: triage-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  request-triage:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Good First Issue') || contains(github.event.pull_request.labels.*.name, 'beginner') }}
    runs-on: ubuntu-latest

    steps:
      - name: Request triage review
        uses: thollander/actions-comment-pull-request@e4a76dd2b0a3c2027c3fd84147a67c22ee4c90fa # v3.0.1
        with:
          message: |
            Requesting triage review from: @hiero-ledger/hiero-sdk-python-triage
          comment-tag: execution
